# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b45929a097e4af2198f5fea412a7a1ed"
name = "Presswall"
application_url = "http://localhost:3000"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "noxify-dvgwvtrt.myshopify.com"

[access_scopes]
scopes = "write_app_proxy"

[auth]
redirect_urls = [
  "http://localhost:3000/api/auth/callback"
]

[app_proxy]
url = "/api/proxy"
subpath = "presswall"
prefix = "apps"

[webhooks]
api_version = "2025-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/api/webhooks"

[pos]
embedded = false
