import { createWordmarkSvg } from "@/lib/publisher-svg";

type SeedPublisher = {
  id: string;
  name: string;
  category: string;
  websiteUrl: string;
  accent?: string;
  sortOrder: number;
};

const SEED_PUBLISHERS: SeedPublisher[] = [
  // Business
  {
    id: "forbes",
    name: "Forbes",
    category: "Business",
    websiteUrl: "https://forbes.com",
    sortOrder: 1,
  },
  {
    id: "inc",
    name: "Inc.",
    category: "Business",
    websiteUrl: "https://inc.com",
    sortOrder: 2,
  },
  {
    id: "fast-company",
    name: "Fast Company",
    category: "Business",
    websiteUrl: "https://fastcompany.com",
    sortOrder: 3,
  },
  {
    id: "entrepreneur",
    name: "Entrepreneur",
    category: "Business",
    websiteUrl: "https://entrepreneur.com",
    sortOrder: 4,
  },
  {
    id: "bloomberg",
    name: "Bloomberg",
    category: "Business",
    websiteUrl: "https://bloomberg.com",
    accent: "#2800d7",
    sortOrder: 5,
  },
  {
    id: "business-insider",
    name: "Business Insider",
    category: "Business",
    websiteUrl: "https://businessinsider.com",
    accent: "#002aff",
    sortOrder: 6,
  },
  {
    id: "yahoo-finance",
    name: "Yahoo Finance",
    category: "Business",
    websiteUrl: "https://finance.yahoo.com",
    accent: "#6001d2",
    sortOrder: 7,
  },
  {
    id: "fortune",
    name: "Fortune",
    category: "Business",
    websiteUrl: "https://fortune.com",
    sortOrder: 8,
  },
  {
    id: "cnbc",
    name: "CNBC",
    category: "Business",
    websiteUrl: "https://cnbc.com",
    accent: "#005594",
    sortOrder: 9,
  },
  {
    id: "marketwatch",
    name: "MarketWatch",
    category: "Business",
    websiteUrl: "https://marketwatch.com",
    sortOrder: 10,
  },
  {
    id: "the-economist",
    name: "The Economist",
    category: "Business",
    websiteUrl: "https://economist.com",
    accent: "#e3120b",
    sortOrder: 11,
  },
  {
    id: "harvard-business-review",
    name: "Harvard Business Review",
    category: "Business",
    websiteUrl: "https://hbr.org",
    accent: "#a41034",
    sortOrder: 12,
  },

  // Tech
  {
    id: "techcrunch",
    name: "TechCrunch",
    category: "Tech",
    websiteUrl: "https://techcrunch.com",
    accent: "#0a9e01",
    sortOrder: 20,
  },
  {
    id: "wired",
    name: "Wired",
    category: "Tech",
    websiteUrl: "https://wired.com",
    sortOrder: 21,
  },
  {
    id: "the-verge",
    name: "The Verge",
    category: "Tech",
    websiteUrl: "https://theverge.com",
    accent: "#e5127d",
    sortOrder: 22,
  },
  {
    id: "mashable",
    name: "Mashable",
    category: "Tech",
    websiteUrl: "https://mashable.com",
    accent: "#00acf0",
    sortOrder: 23,
  },
  {
    id: "cnet",
    name: "CNET",
    category: "Tech",
    websiteUrl: "https://cnet.com",
    accent: "#b80c28",
    sortOrder: 24,
  },
  {
    id: "engadget",
    name: "Engadget",
    category: "Tech",
    websiteUrl: "https://engadget.com",
    sortOrder: 25,
  },
  {
    id: "ars-technica",
    name: "Ars Technica",
    category: "Tech",
    websiteUrl: "https://arstechnica.com",
    accent: "#ff4500",
    sortOrder: 26,
  },
  {
    id: "venturebeat",
    name: "VentureBeat",
    category: "Tech",
    websiteUrl: "https://venturebeat.com",
    accent: "#c4122f",
    sortOrder: 27,
  },
  {
    id: "product-hunt",
    name: "Product Hunt",
    category: "Tech",
    websiteUrl: "https://producthunt.com",
    accent: "#da552f",
    sortOrder: 28,
  },
  {
    id: "zdnet",
    name: "ZDNet",
    category: "Tech",
    websiteUrl: "https://zdnet.com",
    sortOrder: 29,
  },

  // News
  {
    id: "new-york-times",
    name: "The New York Times",
    category: "News",
    websiteUrl: "https://nytimes.com",
    sortOrder: 40,
  },
  {
    id: "wall-street-journal",
    name: "WSJ",
    category: "News",
    websiteUrl: "https://wsj.com",
    sortOrder: 41,
  },
  {
    id: "cnn",
    name: "CNN",
    category: "News",
    websiteUrl: "https://cnn.com",
    accent: "#cc0000",
    sortOrder: 42,
  },
  {
    id: "bbc",
    name: "BBC",
    category: "News",
    websiteUrl: "https://bbc.com",
    accent: "#000000",
    sortOrder: 43,
  },
  {
    id: "the-guardian",
    name: "The Guardian",
    category: "News",
    websiteUrl: "https://theguardian.com",
    accent: "#052962",
    sortOrder: 44,
  },
  {
    id: "washington-post",
    name: "Washington Post",
    category: "News",
    websiteUrl: "https://washingtonpost.com",
    sortOrder: 45,
  },
  {
    id: "usa-today",
    name: "USA Today",
    category: "News",
    websiteUrl: "https://usatoday.com",
    accent: "#009bff",
    sortOrder: 46,
  },
  {
    id: "reuters",
    name: "Reuters",
    category: "News",
    websiteUrl: "https://reuters.com",
    accent: "#ff8000",
    sortOrder: 47,
  },
  {
    id: "associated-press",
    name: "Associated Press",
    category: "News",
    websiteUrl: "https://apnews.com",
    sortOrder: 48,
  },
  {
    id: "nbc-news",
    name: "NBC News",
    category: "News",
    websiteUrl: "https://nbcnews.com",
    sortOrder: 49,
  },

  // Lifestyle & fashion
  {
    id: "vogue",
    name: "Vogue",
    category: "Lifestyle",
    websiteUrl: "https://vogue.com",
    sortOrder: 60,
  },
  {
    id: "gq",
    name: "GQ",
    category: "Lifestyle",
    websiteUrl: "https://gq.com",
    sortOrder: 61,
  },
  {
    id: "elle",
    name: "Elle",
    category: "Lifestyle",
    websiteUrl: "https://elle.com",
    sortOrder: 62,
  },
  {
    id: "refinery29",
    name: "Refinery29",
    category: "Lifestyle",
    websiteUrl: "https://refinery29.com",
    sortOrder: 63,
  },
  {
    id: "cosmopolitan",
    name: "Cosmopolitan",
    category: "Lifestyle",
    websiteUrl: "https://cosmopolitan.com",
    sortOrder: 64,
  },
  {
    id: "oprah-daily",
    name: "Oprah Daily",
    category: "Lifestyle",
    websiteUrl: "https://oprahdaily.com",
    sortOrder: 65,
  },
  {
    id: "instyle",
    name: "InStyle",
    category: "Lifestyle",
    websiteUrl: "https://instyle.com",
    sortOrder: 66,
  },
  {
    id: "who-what-wear",
    name: "Who What Wear",
    category: "Lifestyle",
    websiteUrl: "https://whowhatwear.com",
    sortOrder: 67,
  },
  {
    id: "popsugar",
    name: "POPSUGAR",
    category: "Lifestyle",
    websiteUrl: "https://popsugar.com",
    accent: "#3ec8a4",
    sortOrder: 68,
  },
  {
    id: "town-and-country",
    name: "Town & Country",
    category: "Lifestyle",
    websiteUrl: "https://townandcountrymag.com",
    sortOrder: 69,
  },

  // Beauty
  {
    id: "allure",
    name: "Allure",
    category: "Beauty",
    websiteUrl: "https://allure.com",
    sortOrder: 80,
  },
  {
    id: "byrdie",
    name: "Byrdie",
    category: "Beauty",
    websiteUrl: "https://byrdie.com",
    sortOrder: 81,
  },
  {
    id: "glamour",
    name: "Glamour",
    category: "Beauty",
    websiteUrl: "https://glamour.com",
    sortOrder: 82,
  },
  {
    id: "seventeen",
    name: "Seventeen",
    category: "Beauty",
    websiteUrl: "https://seventeen.com",
    sortOrder: 83,
  },
  {
    id: "new-beauty",
    name: "NewBeauty",
    category: "Beauty",
    websiteUrl: "https://newbeauty.com",
    sortOrder: 84,
  },

  // Wellness & food
  {
    id: "health",
    name: "Health",
    category: "Wellness",
    websiteUrl: "https://health.com",
    accent: "#00a651",
    sortOrder: 90,
  },
  {
    id: "mindbodygreen",
    name: "mindbodygreen",
    category: "Wellness",
    websiteUrl: "https://mindbodygreen.com",
    accent: "#2d6a4f",
    sortOrder: 91,
  },
  {
    id: "well-good",
    name: "Well+Good",
    category: "Wellness",
    websiteUrl: "https://wellandgood.com",
    sortOrder: 92,
  },
  {
    id: "shape",
    name: "Shape",
    category: "Wellness",
    websiteUrl: "https://shape.com",
    sortOrder: 93,
  },
  {
    id: "mens-health",
    name: "Men's Health",
    category: "Wellness",
    websiteUrl: "https://menshealth.com",
    sortOrder: 94,
  },
  {
    id: "womens-health",
    name: "Women's Health",
    category: "Wellness",
    websiteUrl: "https://womenshealthmag.com",
    sortOrder: 95,
  },
  {
    id: "bon-appetit",
    name: "Bon Appétit",
    category: "Food",
    websiteUrl: "https://bonappetit.com",
    sortOrder: 96,
  },
  {
    id: "food-and-wine",
    name: "Food & Wine",
    category: "Food",
    websiteUrl: "https://foodandwine.com",
    sortOrder: 97,
  },
  {
    id: "eating-well",
    name: "EatingWell",
    category: "Food",
    websiteUrl: "https://eatingwell.com",
    sortOrder: 98,
  },

  // TV & entertainment
  {
    id: "shark-tank",
    name: "Shark Tank",
    category: "TV",
    websiteUrl: "https://abc.com/shows/shark-tank",
    accent: "#0072ce",
    sortOrder: 110,
  },
  {
    id: "today-show",
    name: "Today Show",
    category: "TV",
    websiteUrl: "https://today.com",
    accent: "#ff6900",
    sortOrder: 111,
  },
  {
    id: "good-morning-america",
    name: "Good Morning America",
    category: "TV",
    websiteUrl: "https://goodmorningamerica.com",
    accent: "#ffcc00",
    sortOrder: 112,
  },
  {
    id: "the-view",
    name: "The View",
    category: "TV",
    websiteUrl: "https://abc.com/shows/the-view",
    sortOrder: 113,
  },
  {
    id: "ellen",
    name: "The Ellen Show",
    category: "TV",
    websiteUrl: "https://ellen.warnerbros.com",
    sortOrder: 114,
  },
  {
    id: "dr-oz",
    name: "The Dr. Oz Show",
    category: "TV",
    websiteUrl: "https://doctoroz.com",
    sortOrder: 115,
  },
  {
    id: "kelly-clarkson-show",
    name: "The Kelly Clarkson Show",
    category: "TV",
    websiteUrl: "https://kellyclarksonshow.com",
    sortOrder: 116,
  },
  {
    id: "late-night",
    name: "Late Night",
    category: "TV",
    websiteUrl: "https://nbc.com/late-night",
    sortOrder: 117,
  },

  // Media & digital
  {
    id: "buzzfeed",
    name: "BuzzFeed",
    category: "Media",
    websiteUrl: "https://buzzfeed.com",
    accent: "#ee3322",
    sortOrder: 130,
  },
  {
    id: "huffpost",
    name: "HuffPost",
    category: "Media",
    websiteUrl: "https://huffpost.com",
    sortOrder: 131,
  },
  {
    id: "people",
    name: "People",
    category: "Media",
    websiteUrl: "https://people.com",
    sortOrder: 132,
  },
  {
    id: "us-weekly",
    name: "Us Weekly",
    category: "Media",
    websiteUrl: "https://usmagazine.com",
    sortOrder: 133,
  },
  {
    id: "e-news",
    name: "E! News",
    category: "Media",
    websiteUrl: "https://eonline.com",
    accent: "#000000",
    sortOrder: 134,
  },
  {
    id: "tmz",
    name: "TMZ",
    category: "Media",
    websiteUrl: "https://tmz.com",
    sortOrder: 135,
  },
  {
    id: "insider",
    name: "Insider",
    category: "Media",
    websiteUrl: "https://insider.com",
    sortOrder: 136,
  },
  {
    id: "daily-beast",
    name: "The Daily Beast",
    category: "Media",
    websiteUrl: "https://thedailybeast.com",
    sortOrder: 137,
  },
  {
    id: "vice",
    name: "VICE",
    category: "Media",
    websiteUrl: "https://vice.com",
    sortOrder: 138,
  },

  // Retail & deals
  {
    id: "amazon",
    name: "Amazon",
    category: "Retail",
    websiteUrl: "https://amazon.com",
    accent: "#ff9900",
    sortOrder: 150,
  },
  {
    id: "target",
    name: "Target",
    category: "Retail",
    websiteUrl: "https://target.com",
    accent: "#cc0000",
    sortOrder: 151,
  },
  {
    id: "walmart",
    name: "Walmart",
    category: "Retail",
    websiteUrl: "https://walmart.com",
    accent: "#0071ce",
    sortOrder: 152,
  },
  {
    id: "costco",
    name: "Costco",
    category: "Retail",
    websiteUrl: "https://costco.com",
    accent: "#e31837",
    sortOrder: 153,
  },
  {
    id: "qvc",
    name: "QVC",
    category: "Retail",
    websiteUrl: "https://qvc.com",
    accent: "#003da5",
    sortOrder: 154,
  },
  {
    id: "hsn",
    name: "HSN",
    category: "Retail",
    websiteUrl: "https://hsn.com",
    accent: "#00a4e4",
    sortOrder: 155,
  },
  {
    id: "nordstrom",
    name: "Nordstrom",
    category: "Retail",
    websiteUrl: "https://nordstrom.com",
    sortOrder: 156,
  },
  {
    id: "sephora",
    name: "Sephora",
    category: "Retail",
    websiteUrl: "https://sephora.com",
    sortOrder: 157,
  },

  // Podcasts
  {
    id: "joe-rogan-experience",
    name: "The Joe Rogan Experience",
    category: "Podcast",
    websiteUrl: "https://open.spotify.com/show/4rOoJ6Egrf8K2IrywzwOMk",
    sortOrder: 170,
  },
  {
    id: "how-i-built-this",
    name: "How I Built This",
    category: "Podcast",
    websiteUrl: "https://npr.org/podcasts/510313/how-i-built-this",
    sortOrder: 171,
  },
  {
    id: "armchair-expert",
    name: "Armchair Expert",
    category: "Podcast",
    websiteUrl: "https://armchairexpertpod.com",
    sortOrder: 172,
  },
  {
    id: "call-her-daddy",
    name: "Call Her Daddy",
    category: "Podcast",
    websiteUrl: "https://podcasts.apple.com/podcast/call-her-daddy",
    sortOrder: 173,
  },
  {
    id: "smartless",
    name: "SmartLess",
    category: "Podcast",
    websiteUrl: "https://smartless.com",
    sortOrder: 174,
  },
  {
    id: "huberman-lab",
    name: "Huberman Lab",
    category: "Podcast",
    websiteUrl: "https://hubermanlab.com",
    sortOrder: 175,
  },
  {
    id: "the-diary-of-a-ceo",
    name: "The Diary Of A CEO",
    category: "Podcast",
    websiteUrl: "https://stevenbartlett.com/doac",
    sortOrder: 176,
  },

  // Parenting & home
  {
    id: "parents",
    name: "Parents",
    category: "Parenting",
    websiteUrl: "https://parents.com",
    sortOrder: 190,
  },
  {
    id: "motherly",
    name: "Motherly",
    category: "Parenting",
    websiteUrl: "https://mother.ly",
    sortOrder: 191,
  },
  {
    id: "scary-mommy",
    name: "Scary Mommy",
    category: "Parenting",
    websiteUrl: "https://scarymommy.com",
    sortOrder: 192,
  },
  {
    id: "better-homes-gardens",
    name: "Better Homes & Gardens",
    category: "Home",
    websiteUrl: "https://bhg.com",
    sortOrder: 193,
  },
  {
    id: "architectural-digest",
    name: "Architectural Digest",
    category: "Home",
    websiteUrl: "https://architecturaldigest.com",
    sortOrder: 194,
  },
  {
    id: "apartment-therapy",
    name: "Apartment Therapy",
    category: "Home",
    websiteUrl: "https://apartmenttherapy.com",
    accent: "#00a99d",
    sortOrder: 195,
  },

  // Sports
  {
    id: "espn",
    name: "ESPN",
    category: "Sports",
    websiteUrl: "https://espn.com",
    accent: "#cc0000",
    sortOrder: 210,
  },
  {
    id: "sports-illustrated",
    name: "Sports Illustrated",
    category: "Sports",
    websiteUrl: "https://si.com",
    sortOrder: 211,
  },
  {
    id: "bleacher-report",
    name: "Bleacher Report",
    category: "Sports",
    websiteUrl: "https://bleacherreport.com",
    sortOrder: 212,
  },
];

export function getSeedPublishers() {
  return SEED_PUBLISHERS.map((publisher) => ({
    id: publisher.id,
    name: publisher.name,
    category: publisher.category,
    websiteUrl: publisher.websiteUrl,
    sortOrder: publisher.sortOrder,
    logoSvg: createWordmarkSvg(publisher.name, { accent: publisher.accent }),
    logoMonoSvg: createWordmarkSvg(publisher.name, { mono: true }),
  }));
}

export const PUBLISHER_CATEGORIES = [
  "All",
  ...Array.from(
    new Set(SEED_PUBLISHERS.map((publisher) => publisher.category))
  ).sort(),
] as const;

export const CUSTOM_LOGO_TIPS = [
  "Use a transparent PNG or SVG — avoid white or colored box backgrounds.",
  "Horizontal logos work best in the press bar and marquee layouts.",
  "Export at 2× resolution (e.g. 400px wide) so logos stay sharp on retina screens.",
  "SVG is ideal; if using PNG, keep the file under 100 KB per logo.",
] as const;
